// ============================================================================
// Model Configurations - Central configuration for all supported models
// ============================================================================

import type { ModelConfig } from '../types.js';

export const MODEL_CONFIGS: Record<string, ModelConfig> = {
  '@cf/black-forest-labs/flux-1-schnell': {
    id: '@cf/black-forest-labs/flux-1-schnell',
    name: 'FLUX.1 [schnell]',
    description: 'Fast 12B parameter rectified flow transformer for rapid image generation',
    provider: 'black-forest-labs',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'base64',
    supportedTasks: ['text-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      steps: { cfParam: 'steps', type: 'integer', default: 4, min: 1, max: 8 },
      seed: { cfParam: 'seed', type: 'integer' },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 4,
      maxSteps: 8,
      minWidth: 512,
      maxWidth: 2048,
      minHeight: 512,
      maxHeight: 2048,
      supportedSizes: ['512x512', '768x768', '1024x1024'],
    },
  },
  '@cf/black-forest-labs/flux-2-klein-4b': {
    id: '@cf/black-forest-labs/flux-2-klein-4b',
    name: 'FLUX.2 [klein]',
    description: 'Ultra-fast distilled model unifying image generation and editing',
    provider: 'black-forest-labs',
    apiVersion: 2,
    inputFormat: 'multipart',
    responseFormat: 'base64',
    supportedTasks: ['text-to-image', 'image-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      steps: { cfParam: 'steps', type: 'integer', default: 4, min: 1, max: 50 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      image: { cfParam: 'image', type: 'string' },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 4,
      maxSteps: 50,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['256x256', '512x512', '768x768', '1024x1024', '1280x1280'],
    },
  },
  '@cf/black-forest-labs/flux-2-dev': {
    id: '@cf/black-forest-labs/flux-2-dev',
    name: 'FLUX.2 [dev]',
    description: 'High-quality image model with multi-reference support',
    provider: 'black-forest-labs',
    apiVersion: 2,
    inputFormat: 'multipart',
    responseFormat: 'base64',
    supportedTasks: ['text-to-image', 'image-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      steps: { cfParam: 'steps', type: 'integer', default: 20, min: 1, max: 50 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      image: { cfParam: 'image', type: 'string' },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 20,
      maxSteps: 50,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['256x256', '512x512', '768x768', '1024x1024', '1280x1280'],
    },
  },
  '@cf/stabilityai/stable-diffusion-xl-base-1.0': {
    id: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    name: 'Stable Diffusion XL Base 1.0',
    description: 'High-quality diffusion model by Stability AI',
    provider: 'stabilityai',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'binary',
    supportedTasks: ['text-to-image', 'image-to-image', 'inpainting'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      negative_prompt: { cfParam: 'negative_prompt', type: 'string', default: '' },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 20, min: 1, max: 20 },
      guidance: { cfParam: 'guidance', type: 'number', default: 7.5, min: 1, max: 30 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      image_b64: { cfParam: 'image_b64', type: 'string' },
      mask: { cfParam: 'mask', type: 'string' },
      strength: { cfParam: 'strength', type: 'number', default: 1, min: 0, max: 1 },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 20,
      maxSteps: 20,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['256x256', '512x512', '768x768', '1024x1024', '1280x1280', '1024x1792', '1792x1024'],
    },
  },
  '@cf/bytedance/stable-diffusion-xl-lightning': {
    id: '@cf/bytedance/stable-diffusion-xl-lightning',
    name: 'SDXL Lightning',
    description: 'Lightning-fast SDXL model for high-quality 1024px images',
    provider: 'bytedance',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'binary',
    supportedTasks: ['text-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      negative_prompt: { cfParam: 'negative_prompt', type: 'string', default: '' },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 4, min: 1, max: 20 },
      guidance: { cfParam: 'guidance', type: 'number', default: 7.5, min: 1, max: 30 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 4,
      maxSteps: 20,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['512x512', '1024x1024'],
    },
  },
  '@cf/lykon/dreamshaper-8-lcm-8-lcm': {
    id: '@cf/lykon/dreamshaper-8-lcm-8-lcm',
    name: '@cf/lykon/dreamshaper-8-lcm 8 LCM',
    description: 'Enhanced photorealistic SD model with LCM acceleration',
    provider: 'lykon',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'binary',
    supportedTasks: ['text-to-image', 'image-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      negative_prompt: { cfParam: 'negative_prompt', type: 'string', default: '' },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 8, min: 1, max: 20 },
      guidance: { cfParam: 'guidance', type: 'number', default: 7.5, min: 1, max: 30 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      image_b64: { cfParam: 'image_b64', type: 'string' },
      strength: { cfParam: 'strength', type: 'number', default: 1, min: 0, max: 1 },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 8,
      maxSteps: 20,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['512x512', '768x768', '1024x1024'],
    },
  },
  '@cf/leonardo/lucid-origin': {
    id: '@cf/leonardo/lucid-origin',
    name: 'Lucid Origin',
    description: 'Leonardo.AI\'s most adaptable and prompt-responsive model',
    provider: 'leonardo',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'base64',
    supportedTasks: ['text-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      guidance: { cfParam: 'guidance', type: 'number', default: 4.5, min: 0, max: 10 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1120, min: 256, max: 2500, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1120, min: 256, max: 2500, step: 64 },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 4, min: 1, max: 40 },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 4,
      maxSteps: 40,
      minWidth: 256,
      maxWidth: 2500,
      minHeight: 256,
      maxHeight: 2500,
      supportedSizes: ['512x512', '768x768', '1024x1024', '1280x720', '720x1280'],
    },
  },
  '@cf/leonardo/phoenix-1.0': {
    id: '@cf/leonardo/phoenix-1.0',
    name: 'Phoenix 1.0',
    description: 'Leonardo.AI model with exceptional prompt adherence',
    provider: 'leonardo',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'binary',
    supportedTasks: ['text-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      guidance: { cfParam: 'guidance', type: 'number', default: 2, min: 2, max: 10 },
      seed: { cfParam: 'seed', type: 'integer' },
      width: { cfParam: 'width', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 1024, min: 256, max: 2048, step: 64 },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 25, min: 1, max: 50 },
      negative_prompt: { cfParam: 'negative_prompt', type: 'string', default: '' },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 25,
      maxSteps: 50,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['512x512', '768x768', '1024x1024', '1280x1280'],
    },
  },
  '@cf/runwayml/stable-diffusion-v1-5-img2img': {
    id: '@cf/runwayml/stable-diffusion-v1-5-img2img',
    name: 'Stable Diffusion 1.5 Img2Img',
    description: 'Stable Diffusion for image-to-image transformations',
    provider: 'runwayml',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'binary',
    supportedTasks: ['image-to-image'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      negative_prompt: { cfParam: 'negative_prompt', type: 'string', default: '' },
      width: { cfParam: 'width', type: 'integer', default: 512, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 512, min: 256, max: 2048, step: 64 },
      image_b64: { cfParam: 'image_b64', type: 'string' },
      mask_b64: { cfParam: 'mask', type: 'string' },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 20, min: 1, max: 20 },
      strength: { cfParam: 'strength', type: 'number', default: 1, min: 0, max: 1 },
      guidance: { cfParam: 'guidance', type: 'number', default: 7.5, min: 1, max: 30 },
      seed: { cfParam: 'seed', type: 'integer' },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 20,
      maxSteps: 20,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['256x256', '512x512', '768x768', '1024x1024'],
    },
  },
  '@cf/runwayml/stable-diffusion-v1-5-inpainting': {
    id: '@cf/runwayml/stable-diffusion-v1-5-inpainting',
    name: 'Stable Diffusion 1.5 Inpainting',
    description: 'Stable Diffusion for inpainting with mask support',
    provider: 'runwayml',
    apiVersion: 2,
    inputFormat: 'json',
    responseFormat: 'binary',
    supportedTasks: ['inpainting'],
    parameters: {
      prompt: { cfParam: 'prompt', type: 'string', required: true },
      negative_prompt: { cfParam: 'negative_prompt', type: 'string', default: '' },
      width: { cfParam: 'width', type: 'integer', default: 512, min: 256, max: 2048, step: 64 },
      height: { cfParam: 'height', type: 'integer', default: 512, min: 256, max: 2048, step: 64 },
      image_b64: { cfParam: 'image_b64', type: 'string' },
      mask_b64: { cfParam: 'mask', type: 'string' },
      num_steps: { cfParam: 'num_steps', type: 'integer', default: 20, min: 1, max: 20 },
      strength: { cfParam: 'strength', type: 'number', default: 1, min: 0, max: 1 },
      guidance: { cfParam: 'guidance', type: 'number', default: 7.5, min: 1, max: 30 },
      seed: { cfParam: 'seed', type: 'integer' },
    },
    limits: {
      maxPromptLength: 2048,
      defaultSteps: 20,
      maxSteps: 20,
      minWidth: 256,
      maxWidth: 2048,
      minHeight: 256,
      maxHeight: 2048,
      supportedSizes: ['256x256', '512x512', '768x768', '1024x1024'],
    },
  },
};

export function getModelConfig(modelId: string): ModelConfig | null {
  return MODEL_CONFIGS[modelId] || null;
}

export function listModels(): Array<{
  id: string;
  name: string;
  description: string;
  capabilities: string[];
  taskTypes: string[];
}> {
  return Object.values(MODEL_CONFIGS).map((config) => ({
    id: config.id,
    name: config.name,
    description: config.description,
    capabilities: Object.keys(config.parameters),
    taskTypes: config.supportedTasks,
  }));
}
