// Generated by Wrangler by running `wrangler types`

interface Env {
	IMAGE_EXPIRY_HOURS: 24;
	CLOUDFLARE_ACCOUNT_ID: string;
	IMAGE_BUCKET: R2Bucket;
	AI: Ai;
	DEPLOYED_AT?: string;
	COMMIT_SHA?: string;
}
